/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sn.ipsl.bineta.project1;

import java.awt.Color;
import java.awt.ScrollPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author binetAida
 */
public class FormationApp extends javax.swing.JFrame {
    JScrollPane scrollPane=new JScrollPane();
    private static FormationApp instance;
    /**
     * Creates new form FormationApp
     */
    FormationApp() {
        initComponents();
    }

    public static FormationApp getInstance() {
        
        if (instance==null) {
            instance=new FormationApp();
        }
        
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        pan2 = new javax.swing.JPanel();
        pan1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pan4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        elButton = new javax.swing.JButton();
        pan3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        filButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jp2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sortiButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addElevMenuItem = new javax.swing.JMenuItem();
        ListElevMenuItem = new javax.swing.JMenuItem();
        ListEFMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addFilMenuItem = new javax.swing.JMenuItem();
        deleteFilMenuItem = new javax.swing.JMenuItem();
        ModiFilMenuItem = new javax.swing.JMenuItem();
        ListElvNivMenuItem = new javax.swing.JMenuItem();
        ListFMenuItem = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pan2.setBackground(new java.awt.Color(0, 51, 153));
        pan2.setForeground(new java.awt.Color(204, 204, 204));
        pan2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N

        pan1.setBackground(new java.awt.Color(255, 255, 255));
        pan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pan1MouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("       Accueil");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pan1Layout = new javax.swing.GroupLayout(pan1);
        pan1.setLayout(pan1Layout);
        pan1Layout.setHorizontalGroup(
            pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(68, 68, 68))
        );
        pan1Layout.setVerticalGroup(
            pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pan4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pan4MouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(153, 0, 153));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("       Elève");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        elButton.setBackground(new java.awt.Color(204, 204, 204));
        elButton.setForeground(new java.awt.Color(51, 51, 255));
        elButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Camara\\Pictures\\suiven.PNG")); // NOI18N
        elButton.setActionCommand("-->");
        elButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan4Layout = new javax.swing.GroupLayout(pan4);
        pan4.setLayout(pan4Layout);
        pan4Layout.setHorizontalGroup(
            pan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(elButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pan4Layout.setVerticalGroup(
            pan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(elButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pan3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pan3MouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("       Filiére");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        filButton.setBackground(new java.awt.Color(204, 204, 204));
        filButton.setForeground(new java.awt.Color(51, 51, 255));
        filButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Camara\\Pictures\\suiven.PNG")); // NOI18N
        filButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan3Layout = new javax.swing.GroupLayout(pan3);
        pan3.setLayout(pan3Layout);
        pan3Layout.setHorizontalGroup(
            pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(filButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pan3Layout.setVerticalGroup(
            pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" FORMATION");

        javax.swing.GroupLayout pan2Layout = new javax.swing.GroupLayout(pan2);
        pan2.setLayout(pan2Layout);
        pan2Layout.setHorizontalGroup(
            pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pan1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pan2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pan2Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pan2Layout.setVerticalGroup(
            pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(pan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(pan4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(pan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(142, 142, 142))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jp2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenue sur votre menu");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Camara\\Pictures\\livr.PNG")); // NOI18N

        sortiButton.setText("EXIT");
        sortiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp2Layout = new javax.swing.GroupLayout(jp2);
        jp2.setLayout(jp2Layout);
        jp2Layout.setHorizontalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addGap(126, 126, 126))
            .addGroup(jp2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sortiButton)
                .addGap(28, 28, 28))
        );
        jp2Layout.setVerticalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(77, 77, 77)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(137, 137, 137)
                .addComponent(sortiButton)
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setBackground(new java.awt.Color(0, 0, 102));
        jMenu1.setForeground(new java.awt.Color(0, 0, 102));
        jMenu1.setText("Elève");

        addElevMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        addElevMenuItem.setText("Ajout d'un élève");
        addElevMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addElevMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(addElevMenuItem);

        ListElevMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ListElevMenuItem.setText("Liste des élèves");
        ListElevMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListElevMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(ListElevMenuItem);

        ListEFMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ListEFMenuItem.setText("Liste élève d'une Filiere");
        ListEFMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListEFMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(ListEFMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(0, 0, 102));
        jMenu2.setForeground(new java.awt.Color(0, 51, 102));
        jMenu2.setText("Filiére");

        addFilMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        addFilMenuItem.setText("Ajout Filiére");
        addFilMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFilMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(addFilMenuItem);

        deleteFilMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        deleteFilMenuItem.setText("Supprimer Filiére");
        deleteFilMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFilMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(deleteFilMenuItem);

        ModiFilMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ModiFilMenuItem.setText("Modifier Filiére");
        ModiFilMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModiFilMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(ModiFilMenuItem);

        ListElvNivMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ListElvNivMenuItem.setText("Liste élève d'un niveau");
        ListElvNivMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListElvNivMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(ListElvNivMenuItem);

        ListFMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ListFMenuItem.setText("Liste Filiere");
        ListFMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListFMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(ListFMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(pan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteFilMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFilMenuItemActionPerformed
        JPanel contenu= new SupFil();
        JScrollPane scrollPane=new JScrollPane(contenu);
        setContentPane(scrollPane);
        revalidate();
        repaint();
    }//GEN-LAST:event_deleteFilMenuItemActionPerformed

    private void addElevMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addElevMenuItemActionPerformed
       JPanel contenu=new AjoutEleve();
        JScrollPane scrollPane=new JScrollPane(contenu);
        setContentPane(scrollPane);
        revalidate();
        repaint();
    }//GEN-LAST:event_addElevMenuItemActionPerformed

    private void ListElevMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListElevMenuItemActionPerformed
        JPanel contenu=new ListEleve();
        JScrollPane scrollPane=new JScrollPane(contenu);
        setContentPane(scrollPane);
        revalidate();
        repaint();
    }//GEN-LAST:event_ListElevMenuItemActionPerformed

    private void addFilMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFilMenuItemActionPerformed
        JPanel contenu=new AjoutFil();
        JScrollPane scrollPane=new JScrollPane(contenu);
        setContentPane(scrollPane);
        revalidate();
        repaint();
    }//GEN-LAST:event_addFilMenuItemActionPerformed

    private void ModiFilMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModiFilMenuItemActionPerformed
        JPanel contenu=new ModifieFil();
        JScrollPane scrollPane=new JScrollPane(contenu);
        setContentPane(scrollPane);
        revalidate();
        repaint();
    }//GEN-LAST:event_ModiFilMenuItemActionPerformed

    private void ListElvNivMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListElvNivMenuItemActionPerformed
        JPanel contenu=new Recherche();
        JScrollPane scrollPane=new JScrollPane(contenu);
        setContentPane(scrollPane);
        revalidate();
        repaint();
    }//GEN-LAST:event_ListElvNivMenuItemActionPerformed

    private void ListFMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListFMenuItemActionPerformed
        JPanel contenu=new Listfil();
        JScrollPane scrollPane=new JScrollPane(contenu);
        setContentPane(scrollPane);
        revalidate();
        repaint();
    }//GEN-LAST:event_ListFMenuItemActionPerformed

    private void ListEFMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListEFMenuItemActionPerformed
        JPanel contenu=new ListFilEl();
        JScrollPane scrollPane=new JScrollPane(contenu);
        setContentPane(scrollPane);
        revalidate();
        repaint();
    }//GEN-LAST:event_ListEFMenuItemActionPerformed

    private void pan3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan3MouseClicked

        jp2.setVisible(true);
        pan3.setBackground(Color.white);
        pan4.setBackground(new Color(204,204,255));
        pan1.setBackground(new Color(204,204,255));
        FormationApp app=FormationApp.getInstance();
        app.setContentPane(new MenuEleve());
        app.revalidate();
        app.repaint();
    }//GEN-LAST:event_pan3MouseClicked

    private void filButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filButtonActionPerformed
        FormationApp app=FormationApp.getInstance();
        JPanel contenu=new MenuFiliere();
        JScrollPane scrollPane=new JScrollPane(contenu);
        app.setContentPane(scrollPane);
        app.revalidate();
        app.repaint();
    }//GEN-LAST:event_filButtonActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

    }//GEN-LAST:event_jLabel4MouseClicked

    private void pan4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan4MouseClicked

        jp2.setVisible(true);
        pan4.setBackground(Color.white);
        pan1.setBackground(new Color(204,204,255));
        pan3.setBackground(new Color(204,204,255));

    }//GEN-LAST:event_pan4MouseClicked

    private void elButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elButtonActionPerformed
        FormationApp app=FormationApp.getInstance();
        JPanel contenu=new MenuEleve();
        JScrollPane scrollPane=new JScrollPane(contenu);
        app.setContentPane(scrollPane);
        app.revalidate();
        app.repaint();
    }//GEN-LAST:event_elButtonActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

    }//GEN-LAST:event_jLabel3MouseClicked

    private void pan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan1MouseClicked

        jp2.setVisible(true);
        pan1.setBackground(Color.white);
        pan4.setBackground(new Color(204,204,255));
        pan3.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_pan1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

    }//GEN-LAST:event_jLabel2MouseClicked

    private void sortiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortiButtonActionPerformed
    if(evt.getSource()==sortiButton){
        this.setVisible(false);
        this.dispose();
    }
    }//GEN-LAST:event_sortiButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormationApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormationApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormationApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormationApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormationApp.getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ListEFMenuItem;
    private javax.swing.JMenuItem ListElevMenuItem;
    private javax.swing.JMenuItem ListElvNivMenuItem;
    private javax.swing.JMenuItem ListFMenuItem;
    private javax.swing.JMenuItem ModiFilMenuItem;
    private javax.swing.JMenuItem addElevMenuItem;
    private javax.swing.JMenuItem addFilMenuItem;
    private javax.swing.JMenuItem deleteFilMenuItem;
    private javax.swing.JButton elButton;
    private javax.swing.JButton filButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel jp2;
    private javax.swing.JPanel pan1;
    private javax.swing.JPanel pan2;
    private javax.swing.JPanel pan3;
    private javax.swing.JPanel pan4;
    private javax.swing.JButton sortiButton;
    // End of variables declaration//GEN-END:variables
}
