/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sn.ipsl.bineta.project1;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author binetAida
 */
public class MenuFiliere extends javax.swing.JPanel {

    /**
     * Creates new form MenuFiliere
     */
    
    public void close(){
    SwingUtilities.getWindowAncestor(MenuFiliere.this).dispose();
    }
    

    public MenuFiliere() {
        initComponents();
        JButton bouton= sortiButton;
        bouton.addActionListener(e-> close());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AjFButton = new javax.swing.JButton();
        ModiButton = new javax.swing.JButton();
        SupButton = new javax.swing.JButton();
        LisFButton = new javax.swing.JButton();
        LisEFButton = new javax.swing.JButton();
        sortiButton = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Camara\\Pictures\\Ajoutf.PNG")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Camara\\Pictures\\modifi.PNG")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Camara\\Pictures\\supp.PNG")); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Camara\\Pictures\\ecol.PNG")); // NOI18N

        AjFButton.setBackground(new java.awt.Color(255, 255, 255));
        AjFButton.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        AjFButton.setText("Ajout d'une Filiere");
        AjFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjFButtonActionPerformed(evt);
            }
        });

        ModiButton.setBackground(new java.awt.Color(255, 255, 255));
        ModiButton.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        ModiButton.setText("Modifier une Filiere");
        ModiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModiButtonActionPerformed(evt);
            }
        });

        SupButton.setBackground(new java.awt.Color(255, 255, 255));
        SupButton.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        SupButton.setText("Supprimer une Filiere");
        SupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupButtonActionPerformed(evt);
            }
        });

        LisFButton.setBackground(new java.awt.Color(255, 255, 255));
        LisFButton.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        LisFButton.setText("Liste des Filieres");
        LisFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LisFButtonActionPerformed(evt);
            }
        });

        LisEFButton.setBackground(new java.awt.Color(255, 255, 255));
        LisEFButton.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        LisEFButton.setText("Liste des élèves d'une Classe");
        LisEFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LisEFButtonActionPerformed(evt);
            }
        });

        sortiButton.setText("EXIT");
        sortiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(AjFButton)
                                .addGap(79, 79, 79)
                                .addComponent(LisFButton))
                            .addComponent(jLabel4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(LisEFButton)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SupButton)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ModiButton)
                        .addGap(124, 124, 124))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sortiButton)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel2)))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LisFButton)
                            .addComponent(AjFButton))
                        .addGap(52, 52, 52)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ModiButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LisEFButton)
                    .addComponent(SupButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(sortiButton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AjFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjFButtonActionPerformed
       FormationApp app=FormationApp.getInstance();
       JPanel contenu=new AjoutFil();
        JScrollPane scrollPane=new JScrollPane(contenu);
        app.setContentPane(scrollPane);
        app.revalidate();
        app.repaint();
    }//GEN-LAST:event_AjFButtonActionPerformed

    private void LisFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LisFButtonActionPerformed
        FormationApp app=FormationApp.getInstance();
        JPanel contenu=new Listfil();
        JScrollPane scrollPane=new JScrollPane(contenu);
        app.setContentPane(scrollPane);
        app.revalidate();
        app.repaint();
    }//GEN-LAST:event_LisFButtonActionPerformed

    private void ModiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModiButtonActionPerformed
        FormationApp app=FormationApp.getInstance();
        JPanel contenu=new ModifieFil();
        JScrollPane scrollPane=new JScrollPane(contenu);
        app.setContentPane(scrollPane);
        app.revalidate();
        app.repaint();
    }//GEN-LAST:event_ModiButtonActionPerformed

    private void SupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupButtonActionPerformed
        FormationApp app=FormationApp.getInstance();
        JPanel contenu=new SupFil();
        JScrollPane scrollPane=new JScrollPane(contenu);
        app.setContentPane(scrollPane);
        app.revalidate();
        app.repaint();
    }//GEN-LAST:event_SupButtonActionPerformed

    private void LisEFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LisEFButtonActionPerformed
        FormationApp app=FormationApp.getInstance();
        JPanel contenu=new Recherche();
        JScrollPane scrollPane=new JScrollPane(contenu);
        app.setContentPane(scrollPane);
        app.revalidate();
        app.repaint();
    }//GEN-LAST:event_LisEFButtonActionPerformed

    private void sortiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortiButtonActionPerformed
        close();
    }//GEN-LAST:event_sortiButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjFButton;
    private javax.swing.JButton LisEFButton;
    private javax.swing.JButton LisFButton;
    private javax.swing.JButton ModiButton;
    private javax.swing.JButton SupButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton sortiButton;
    // End of variables declaration//GEN-END:variables
}
